basket/urls.py
from django.conf.urls import url
from basket import views
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



app_name = 'Game'

urlpatterns = [
    path('players/list', views.players_list, name="players_list"),   
    path('teams/list', views.teams_list, name="teams_list"),   
    path('coachs/list', views.coachs_list, name="coachs_list"),   
    path('matchs/list', views.matchs_list, name="matchs_list"),

    path('Coach/a', views.indexCoach, name='indexCoach'),
    path('Coach/add/', views.Coach_create, name='Coach_add'),
    path('Coach/update/<int:pk>', views.Coach_update, name='Coach_update'),
    path('Coach/delete/<int:pk>', views.Coach_delete, name='Coach_delete'),

    path('Team/a', views.indexTeam, name='indexTeam'),
    path('Team/add/', views.Team_create, name='Team_create'),
    path('Team/update/<int:pk>', views.Team_update, name='Team_update'),
    path('Team/delete/<int:pk>', views.Team_delete, name='Team_delete'),

    path('Player/a', views.indexPlayer, name='indexPlayer'),
    path('Player/add/', views.Player_create, name='Player_add'),
    path('Player/update/<int:pk>', views.Player_update, name='Player_update'),
    path('Player/delete/<int:pk>', views.Player_delete, name='Player_delete'),
    path('', views.home, name="home"),   

    path('Mi_Perfil' , views.pperfil , name="Perfil" ),
    path('registro' , views.registro_view , name="registro" ),
    path('login', views.login, name="login"),
    path('logout', views.logout ,name="logout"),
    path('ChangePassword', views.ChangePassword ,name="ChangePassword"),
    


]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from basket import views as wena

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basket.urls')),
    path('login', wena.login, name="login"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/acciones/Player_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Players</title> 
{% endblock %}


{% block antes_del_body%}
        <div align="right">
            <br>

        </div>
{% endblock %}


{% block body %}

{% if request.user.is_staff  %}
<a href="{% url 'Game:home' %}">back to home</a><br>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>name</th>
      <th>nickname</th>
      <th>birthday</th>
      <th>age</th>
      <th>rut</th>
      <th>email</th>
      <th>height</th>
      <th>weight</th>
      <th>photo</th>
      <th>team</th>
      <th>position</th>
      <th>Activity</th>
    </tr>
  </thead>
  <tbody>
    <a href="{% url 'Game:Player_add' %}">add</a>
    {% for b in Player %}
    <tr>
      <td>{{ b.name }}</td>
      <td>{{ b.nickname }}</td>
      <td>{{ b.birthday }}</td>
      <td>{{ b.age }}</td>
      <td>{{ b.rut }}</td>
      <td>{{ b.email }}</td>
      <td>{{ b.height }}</td>
      <td>{{ b.weight }}</td>
      <td><img src="{{ b.photo }}"  alt="" height="100px" width="100px"  class="rounded-circle"></td>
      <td>{{ b.team }}</td>
      <td>{{ b.position }}</td>

      <td>
        <a href="{% url 'Game:Player_update' b.id %}">edit</a>
        <a href="{% url 'Game:Player_delete' b.id %}">delete</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<a href="{% url 'Game:home' %}">back to home</a><br>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>name</th>
      <th>nickname</th>
      <th>birthday</th>
      <th>age</th>
      <th>rut</th>
      <th>email</th>
      <th>height</th>
      <th>weight</th>
      <th>photo</th>
      <th>team</th>
      <th>position</th>

    </tr>
  </thead>
  <tbody>

    {% for b in Player %}
    <tr>
      <td>{{ b.name }}</td>
      <td>{{ b.nickname }}</td>
      <td>{{ b.birthday }}</td>
      <td>{{ b.age }}</td>
      <td>{{ b.rut }}</td>
      <td>{{ b.email }}</td>
      <td>{{ b.height }}</td>
      <td>{{ b.weight }}</td>
      <td><img src="{{ b.photo }}"  alt="" height="100px" width="100px"  class="rounded-circle"></td>
      <td>{{ b.team }}</td>
      <td>{{ b.position }}</td>

    </tr>
    {% endfor %}
  </tbody>
</table>

{% endif %}

{% endblock %}

templates/acciones/Team_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Teams</title> 
{% endblock %}


{% block antes_del_body%}
        <div align="right">
            <br>

        </div>
{% endblock %}


{% block body %}
{% if request.user.is_staff  %}
<a href="{% url 'Game:home' %}">back to home</a><br>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>name</th>
      <th>description</th>
      <th>code</th>
      <th>coach</th>
      <th>Activity</th>
    </tr>
  </thead>
  <tbody>
    <a href="{% url 'Game:Team_create' %}">add</a>
    {% for b in teams %}
    <tr>
      <td>{{ b.name }}</td>
      <td>{{ b.description }}</td>
      <td>{{ b.code }}</td>
      <td>{{ b.coach }}</td>
      <td><img src="{{ b.photo }}"  alt="" height="100px" width="100px"  class="rounded-circle"></td>
      <td>
        <a href="{% url 'Game:Team_update' b.id %}">edit</a>
        <a href="{% url 'Game:Team_delete' b.id %}">delete</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<a href="{% url 'Game:home' %}">back to home</a><br>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>name</th>
      <th>description</th>
      <th>code</th>
      <th>coach</th>
      
    </tr>
  </thead>
  <tbody>
    <a href="{% url 'Game:Team_create' %}">add</a>
    {% for b in teams %}
    <tr>
      <td>{{ b.name }}</td>
      <td>{{ b.description }}</td>
      <td>{{ b.code }}</td>
      <td>{{ b.coach }}</td>
      <td><img src="{{ b.photo }}"  alt="" height="100px" width="100px"  class="rounded-circle"></td>
  
    </tr>
    {% endfor %}
  </tbody>

{% endif %}

{% endblock %}

templates/acciones/cambio_pass.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Registrar </title>
{% endblock %}


{% block antes_del_body%}

{% endblock %}


{% block body %}
<br>

<h2>Cambiar Contraseña</h2>
                <!-- Formulario-->
                <form method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button class="btn btn-primary" type="submit">Guardar Cambios</button>
                  </form>


    

{% endblock %}

templates/acciones/delete.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}
{% block body %}
{% csrf_token %}
<form class="" method="post">
  {% csrf_token %}
  Are you sure want to delete it?
  <input type="submit" name="" value="submit">
</form>
{% endblock %}

templates/acciones/form.html
{% extends 'base.html' %}
{% block title %}
fbv form
{% endblock %}
{% block body %}
{% csrf_token %}
<form  method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" name="" value="submit">
</form>
{% endblock %}

templates/acciones/list_coach.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Inicio</title> 
{% endblock %}


{% block antes_del_body%}
        <div align="right">
            <br>

        </div>
{% endblock %}


{% block body %}
{% if request.user.is_staff  %}
  <a href="{% url 'Game:home' %}">back to home</a><br>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>name</th>
        <th>age</th>
        <th>email</th>
        <th>rut</th>
        <th>nickname</th>
        <th>Acciones</th>

      </tr>
    </thead>
    <tbody>
      <a href="{% url 'Game:Coach_add' %}">add</a>
      {% for b in Coach %}
      <tr>
        <td>{{ b.user }}</td>
        <td>{{ b.age }}</td>
        <td>{{ b.email }}</td>
        <td>{{ b.rut }}</td>
        <td>{{ b.user }}</td>
        <td>
          <a href="{% url 'Game:Coach_update' b.id %}">edit</a>
          <a href="{% url 'Game:Coach_delete' b.id %}">delete</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <a href="{% url 'Game:home' %}">back to home</a><br>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>name</th>
        <th>age</th>
        <th>email</th>
        <th>rut</th>
        <th>nickname</th>


      </tr>
    </thead>
    <tbody>

      {% for b in Coach %}
      <tr>
        <td>{{ b.user }}</td>
        <td>{{ b.age }}</td>
        <td>{{ b.email }}</td>
        <td>{{ b.rut }}</td>
        <td>{{ b.user }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endif %}
{% endblock %}

templates/acciones/matchs_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Inicio</title> 
{% endblock %}


{% block antes_del_body%}
        <div align="right">
            <br>

        </div>
{% endblock %}


{% block body %}
    <body>
        <ul>
            {% for match in matchs %}
            <br>
            <br>
            <li>{{match.team1.player.first.team.name}} <strong>VS</strong> {{match.team2.player.first.team.name}}</li>
            <br>
            <br>
            {% endfor %}
        </ul>
    </body>
    {% endblock %}

templates/acciones/miperfil.html
{% extends 'base.html' %}
{% load static %}
{% block head %}

{% endblock %}

{% block body %}

<br>
<div align="center">
    <img src="{{ Profile.image }}" align="center" alt="" height="200px" width="200px" class="rounded-circle">
</div>
<table class="table table-bordered">
  <thead>
  </thead>
  <tbody>
    <br>
    <br>

    {% if Profile %}
    <tr>
      <td>Nombre de Usuario : </td>
      <td>{{ Userr.username}}</td>
    </tr>
    <tr>
      <td>Nombre :</td>
      <td>{{ Userr.first_name}}</td>
    </tr>
    <tr>
      <td>Apellido : </td>
      <td>{{ Userr.last_name}}</td>
    </tr>
    <tr>
      <td>Rut : </td>
      <td>{{ Profile.rut}}</td>
    </tr>
    <tr>
      <td>Email : </td>
      <td>{{ Userr.email}}</td>
    </tr>
        {% else %}
        <tr>
          <td>Nombre de Usuario : </td>
          <td>{{ Userr.username}}</td>
        </tr>
        <tr>
          <td>Nombre :</td>
          <td>{{ Userr.first_name}}</td>
        </tr>
        <tr>
          <td>Apellido : </td>
          <td>{{ Userr.last_name}}</td>
        </tr>
        <tr>
          <td>Email : </td>
          <td>{{ Userr.email}}</td>
        </tr>


        {% endif %}


  </tbody>
</table>
<div align="center";><a role="button" class="btn btn-primary" href="#">Editar Perfil</a></div>

{% endblock %}

templates/acciones/registrar.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Registrar </title>
{% endblock %}


{% block antes_del_body%}

{% endblock %}


{% block body %}
<br>

<h2>Registrar</h2>
                <form method="post">

                    {% csrf_token %}
                    <br>
                            {% for field in form %}
                                <div>
                                    {{field.label_tag}}
                                    {{field}}

                                    {% if field.errors %}
                                        {{ field.errors }}
                                    {% endif %}
                                </div>
                                <br>
                                
                            {% endfor %}
                            <br>
                            <button type="submit" class="btn btn-primary">Registrar</button>
                        </from>


                </form>

{% endblock %}