basket/urls.py
from django.conf.urls import url
from basket import views
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



app_name = 'Game'

urlpatterns = [
    path('players/list', views.players_list, name="players_list"),   
    path('teams/list', views.teams_list, name="teams_list"),   
    path('coachs/list', views.coachs_list, name="coachs_list"),   
    path('matchs/list', views.matchs_list, name="matchs_list"),

    path('Coach/a', views.indexCoach, name='indexCoach'),
    path('Coach/add/', views.Coach_create, name='Coach_add'),
    path('Coach/update/<int:pk>', views.Coach_update, name='Coach_update'),
    path('Coach/delete/<int:pk>', views.Coach_delete, name='Coach_delete'),

    path('Team/a', views.indexTeam, name='indexTeam'),
    path('Team/add/', views.Team_create, name='Team_create'),
    path('Team/update/<int:pk>', views.Team_update, name='Team_update'),
    path('Team/delete/<int:pk>', views.Team_delete, name='Team_delete'),

    path('Player/a', views.indexPlayer, name='indexPlayer'),
    path('Player/add/', views.Player_create, name='Player_add'),
    path('Player/update/<int:pk>', views.Player_update, name='Player_update'),
    path('Player/delete/<int:pk>', views.Player_delete, name='Player_delete'),
    path('', views.home, name="home"),   

    path('Mi_Perfil' , views.pperfil , name="Perfil" ),
    path('registro' , views.registro_view , name="registro" ),
    path('login', views.login, name="login"),
    path('logout', views.logout ,name="logout"),
    path('ChangePassword', views.ChangePassword ,name="ChangePassword"),
    


]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from basket import views as wena

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basket.urls')),
    path('login', wena.login, name="login"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset='utf-8'>
        {% block head %}
        {% endblock %}

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    </head>


    <body class='fondo'> 
        {% include 'navbar.html' %}
        {% include 'messagess.html' %}
        
        {% block antes_del_body%}

        {% endblock %}
        <div class="container">
            <div class="row">
                <div class="col">
                    {% block body %}

                    {% endblock %}
                </div>
            </div>
        </div>
        
    </body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/471ef0948e.js" crossorigin="anonymous"></script>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Inicio</title> 
{% endblock %}


{% block antes_del_body%}
        <div align="right">
            <br>

        </div>
{% endblock %}


{% block body %}    
<br>
<br>
<h1>Basket App</h1>
<br>
<br>
<br>


<ul>
    <a href="{% url 'Game:indexCoach' %}"> Entrenadores</a>
    <br>
    <a href="{% url 'Game:indexTeam' %}">Equipos</a>
    <br>
    <a href="{% url 'Game:indexPlayer' %}">Jugadores</a>
    <br>
    <a href="{% url 'Game:matchs_list' %}">Partidas jugadas</a>
    <br>

</ul>
<h2>Last 5 players</h2>
    
<ul>
    {% for player in last_5_players %}
    <li>{{player.name}} ({{player.nickname}})</li>
    {% endfor %}
</ul>

<h2>Last 5 Matchs</h2>
<ul>
    {% for match in last_5_matchs %}
    <li>{{match.team1.player.first.team.name}} <strong>VS</strong> {{match.team2.player.first.team.name}}</li>
    {% endfor %}
</ul>

<h2>Teams</h2>
<ul>
    {% for team in teams %}
    <li>{{team.name}} (tiene {{team.count_player}} jugadores)</li>
    {% endfor %}
</ul>
  
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Inicio</title> 
{% endblock %}


{% block antes_del_body%}
        <div align="right">
            <br>

        </div>
{% endblock %}


{% block body %}    

<br>
<h2>Iniciar Sesión</h2>
<!-- Formulario-->
<form method="post">

    {% csrf_token %}
    <br>
    <div class="form-group">
        <label for="username">Nombre de usuario:</label>
        <input type="text" name="username"class="form-control">
    </div>
     
    <div class="form-group">
        <label for="password">Contraseña:</label>
        <input type="password" name="password"class="form-control">
    </div>
    <br>
   
    <button type="submit" class="btn btn-primary">Iniciar Sesión</button>

</form>
{% endblock %}

templates/matchs_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Inicio</title> 
{% endblock %}


{% block antes_del_body%}
        <div align="right">
            <br>

        </div>
{% endblock %}


{% block body %}
    <body>
        <ul>
            {% for match in matchs %}
            <br>
            <br>
            <li>{{match.team1.player.first.team.name}} <strong>VS</strong> {{match.team2.player.first.team.name}}</li>
            <br>
            <br>
            {% endfor %}
        </ul>
    </body>
    {% endblock %}

templates/messagess.html
{% if messages %}
{% for message in messages %}
    <div class="alert {% if message.tags ==  'success' %} alert-success {% else %} alert-danger {% endif %}">
        <button type="button" class="close" data-dismiss="alert">x</button>
        {{ message }}
    </div>
{% endfor %}
{% endif %}

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    
    <a class="navbar-brand" href="{% url 'Game:home' %}">
        <img src="{% static 'img/33838.png' %}"  alt="Basket App" height="100px" width="100px"  class="rounded-circle">
    </a>
    

    <button type="button" name="button" class="navbar-toggler navbar-toggler-right" data-toggler="colapse" data-target="#navbar">
        <span class="navbar-toggler-icon"></span>
    </button>

 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
            {% if request.user.is_staff  %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Game:home' %}">Inicio </a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Game:indexCoach' %}">Entrenadores</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Game:indexTeam' %}">Equipos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Game:indexPlayer' %}">Jugadores</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Game:matchs_list' %}">Partidas Jugadas</a>
                </li>
                {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Game:matchs_list' %}">Partidas Jugadas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Game:indexTeam' %}">Equipos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Game:indexPlayer' %}">Jugadores</a>
                </li>

            {% endif %}
        {% endif %}
        
        </ul>
    </div>
    

    <div id="navb" class="navbar-collapse collapse hide">
        <ul class="nav navbar-nav ml-auto">

                
            {% if user.is_authenticated %}
            <li class="navbar-item">
                <a href="{% url 'Game:Perfil' %}" class="nav-link">
                    <span class="fa fa-user"></span>
                    Mi Perfil</a>
            </li>
            <li class="navbar-item">
                <a href="{% url 'Game:ChangePassword' %}" class="nav-link">
                    <span class="fa fa-user"></span>
                    Cambiar Contraseña</a>
            </li>
            <li class="navbar-item">
                <a href="{% url 'Game:logout' %}" class="nav-link">
                    <span class="fa fa-sign-in-alt"></span>
                    Cerrar Sesión</a>
            </li>
        {% else %}
            <li class="navbar-item">
                <a href="{% url 'Game:login' %}" class="nav-link">
                    <span class="fa fa-user"></span> 
                    Iniciar Sesión</a>
            </li>
            <li class="navbar-item">
                <a href="{% url 'Game:registro' %}" class="nav-link ">
                    <span class="fa fa-user-plus"></span>
                    Registro entrenador</a>
            </li>
        {% endif %}
        
    </ul>
</div>


          
            
    

</nav>